"""Improvement Log — the agent's self-improvement proposal system.

After each evening reflection, the agent writes concrete proposals for
how to improve its own trading system. These accumulate in a README file
per strategist profile that a human developer can review and action.

The agent is its own product manager: it identifies gaps in its data,
strategies, risk rules, and infrastructure — then proposes fixes.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def append_improvement_proposals(
    proposals: list[dict[str, Any]],
    *,
    data_dir: str = "data",
    profile_id: str = "default",
    date: str | None = None,
) -> Path:
    """Append self-improvement proposals to the strategist's IMPROVEMENT_PROPOSALS.md.

    Each proposal has: category, priority, title, description, expected_impact.
    The file is append-only — new proposals go at the top so the most recent
    are visible first.

    Args:
        proposals: List of proposal dicts from the evening reflection.
        data_dir: Profile data directory.
        profile_id: Strategist profile ID (for the header).
        date: Override date (defaults to today UTC).

    Returns:
        Path to the updated file.
    """
    if not proposals:
        return Path(data_dir) / "IMPROVEMENT_PROPOSALS.md"

    today = date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    root = Path(data_dir)
    filepath = root / "IMPROVEMENT_PROPOSALS.md"

    # Build the new section
    lines = [
        f"\n## {today} — Evening Reflection Proposals\n",
    ]

    for p in proposals:
        category = p.get("category", "other")
        priority = p.get("priority", "medium")
        title = p.get("title", "Untitled proposal")
        description = p.get("description", "")
        impact = p.get("expected_impact", "")

        priority_badge = {"high": "HIGH", "medium": "MED", "low": "LOW"}.get(
            priority, "MED"
        )

        lines.append(f"### [{priority_badge}] [{category}] {title}\n")
        if description:
            lines.append(f"{description}\n")
        if impact:
            lines.append(f"**Expected impact:** {impact}\n")
        lines.append("")

    new_section = "\n".join(lines)

    # Read existing content (if any) and prepend new proposals after header
    header = (
        f"# Improvement Proposals — {profile_id} Strategist\n\n"
        "This file is auto-generated by the agent's evening reflection.\n"
        "Each night the agent thinks about what would make it better and writes proposals here.\n"
        "Review these periodically and implement the high-priority ones.\n\n"
        "---\n"
    )

    if filepath.exists():
        existing = filepath.read_text(encoding="utf-8")
        # Strip existing header to avoid duplication
        if existing.startswith("# Improvement Proposals"):
            # Find the --- separator
            sep_idx = existing.find("---\n")
            if sep_idx >= 0:
                body = existing[sep_idx + 4:]
            else:
                body = existing
        else:
            body = existing
        content = header + new_section + "\n" + body
    else:
        root.mkdir(parents=True, exist_ok=True)
        content = header + new_section

    filepath.write_text(content, encoding="utf-8")
    logger.info("Appended %d improvement proposals to %s", len(proposals), filepath)

    # Also save structured JSON for programmatic access
    _save_proposals_json(proposals, data_dir=data_dir, date=today)

    return filepath


def _save_proposals_json(
    proposals: list[dict], *, data_dir: str, date: str
) -> None:
    """Append proposals to a JSON log for programmatic access."""
    json_path = Path(data_dir) / "improvement_proposals.json"
    existing: list[dict] = []
    if json_path.exists():
        try:
            existing = json.loads(json_path.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    entry = {
        "date": date,
        "proposals": proposals,
    }
    existing.append(entry)

    # Keep last 90 days of proposals
    existing = existing[-90:]
    json_path.write_text(json.dumps(existing, indent=2, default=str))


def get_pending_proposals(
    data_dir: str = "data",
    *,
    min_priority: str = "low",
    category: str | None = None,
) -> list[dict]:
    """Load all pending proposals, optionally filtered.

    Returns flat list of proposals with their dates.
    """
    json_path = Path(data_dir) / "improvement_proposals.json"
    if not json_path.exists():
        return []

    try:
        entries = json.loads(json_path.read_text())
    except (json.JSONDecodeError, OSError):
        return []

    priority_order = {"high": 3, "medium": 2, "low": 1}
    min_level = priority_order.get(min_priority, 0)

    results = []
    for entry in entries:
        date = entry.get("date", "")
        for p in entry.get("proposals", []):
            level = priority_order.get(p.get("priority", "low"), 0)
            if level < min_level:
                continue
            if category and p.get("category") != category:
                continue
            results.append({**p, "date": date})

    return results
