"""Improvement Log — the agent's self-improvement proposal system.

After each evening reflection, the agent writes concrete proposals for
how to improve its own trading system. These accumulate in a README file
per strategist profile that a human developer can review and action.

The agent is its own product manager: it identifies gaps in its data,
strategies, risk rules, and infrastructure — then proposes fixes.

Proposal schema (all fields optional except category/priority/title):
{
    "category": "strategy|threshold|data_source|risk_rule|infrastructure|other",
    "priority": "high|medium|low",
    "title": "Short title",
    "description": "What to change and why",
    "expected_impact": "How this improves trading",
    "implementation_hint": {            # Optional — added by evolve phase
        "file": "src/.../strategy_agent.py",
        "function": "_check_momentum",
        "current_value": "rsi < 35",
        "proposed_value": "rsi < 25",
        "type": "threshold_adjustment|new_function|new_data_source|config_change"
    },
    "evidence": {                       # Optional — added by evolve phase
        "sample_size": 12,
        "win_rate_current": 0.33,
        "dates": ["2026-03-19", "2026-03-20"]
    },
    "status": "pending|accepted|rejected|implemented",
    "created_date": "YYYY-MM-DD"
}
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def append_improvement_proposals(
    proposals: list[dict[str, Any]],
    *,
    data_dir: str = "data",
    profile_id: str = "default",
    date: str | None = None,
) -> Path:
    """Append self-improvement proposals to the strategist's IMPROVEMENT_PROPOSALS.md.

    Each proposal has: category, priority, title, description, expected_impact.
    The file is append-only — new proposals go at the top so the most recent
    are visible first.

    Args:
        proposals: List of proposal dicts from the evening reflection.
        data_dir: Profile data directory.
        profile_id: Strategist profile ID (for the header).
        date: Override date (defaults to today UTC).

    Returns:
        Path to the updated file.
    """
    if not proposals:
        return Path(data_dir) / "IMPROVEMENT_PROPOSALS.md"

    today = date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    root = Path(data_dir)
    filepath = root / "IMPROVEMENT_PROPOSALS.md"

    # Build the new section
    lines = [
        f"\n## {today} — Evening Reflection Proposals\n",
    ]

    for p in proposals:
        category = p.get("category", "other")
        priority = p.get("priority", "medium")
        title = p.get("title", "Untitled proposal")
        description = p.get("description", "")
        impact = p.get("expected_impact", "")

        priority_badge = {"high": "HIGH", "medium": "MED", "low": "LOW"}.get(
            priority, "MED"
        )

        lines.append(f"### [{priority_badge}] [{category}] {title}\n")
        if description:
            lines.append(f"{description}\n")
        if impact:
            lines.append(f"**Expected impact:** {impact}\n")
        lines.append("")

    new_section = "\n".join(lines)

    # Read existing content (if any) and prepend new proposals after header
    header = (
        f"# Improvement Proposals — {profile_id} Strategist\n\n"
        "This file is auto-generated by the agent's evening reflection.\n"
        "Each night the agent thinks about what would make it better and writes proposals here.\n"
        "Review these periodically and implement the high-priority ones.\n\n"
        "---\n"
    )

    if filepath.exists():
        existing = filepath.read_text(encoding="utf-8")
        # Strip existing header to avoid duplication
        if existing.startswith("# Improvement Proposals"):
            # Find the --- separator
            sep_idx = existing.find("---\n")
            if sep_idx >= 0:
                body = existing[sep_idx + 4:]
            else:
                body = existing
        else:
            body = existing
        content = header + new_section + "\n" + body
    else:
        root.mkdir(parents=True, exist_ok=True)
        content = header + new_section

    filepath.write_text(content, encoding="utf-8")
    logger.info("Appended %d improvement proposals to %s", len(proposals), filepath)

    # Also save structured JSON for programmatic access
    _save_proposals_json(proposals, data_dir=data_dir, date=today)

    return filepath


def _save_proposals_json(
    proposals: list[dict], *, data_dir: str, date: str
) -> None:
    """Append proposals to a JSON log for programmatic access."""
    json_path = Path(data_dir) / "improvement_proposals.json"
    existing: list[dict] = []
    if json_path.exists():
        try:
            existing = json.loads(json_path.read_text(encoding="utf-8-sig"))
        except (json.JSONDecodeError, OSError):
            pass

    # Stamp status and created_date on proposals that don't have them
    stamped = []
    for p in proposals:
        stamped.append({
            "status": "pending",
            "created_date": date,
            **p,  # proposal fields override defaults
        })

    entry = {
        "date": date,
        "proposals": stamped,
    }
    existing.append(entry)

    # Keep last 90 days of proposals
    existing = existing[-90:]
    json_path.write_text(json.dumps(existing, indent=2, default=str))


def save_evolution_proposals(
    proposals: list[dict[str, Any]],
    *,
    data_dir: str = "data",
    profile_id: str = "default",
    date: str | None = None,
) -> Path:
    """Save enriched evolution proposals (with implementation_hint and evidence).

    These come from the evolve phase and are richer than evening reflection proposals.
    Also generates EVOLUTION_REPORT.md as a human-readable action list.
    """
    if not proposals:
        return Path(data_dir) / "EVOLUTION_REPORT.md"

    today = date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    root = Path(data_dir)
    root.mkdir(parents=True, exist_ok=True)

    # Save to the same JSON log (backward compatible)
    append_improvement_proposals(proposals, data_dir=data_dir, profile_id=profile_id, date=today)

    # Generate EVOLUTION_REPORT.md
    report_path = root / "EVOLUTION_REPORT.md"
    lines = [
        f"# Evolution Report — {profile_id} Strategist\n",
        f"Generated: {today}\n\n",
        "This report contains evidence-backed proposals from the evolution phase.\n"
        "Each proposal includes the specific file and change needed.\n\n",
        "---\n",
    ]

    high = [p for p in proposals if p.get("priority") == "high"]
    medium = [p for p in proposals if p.get("priority") == "medium"]
    low = [p for p in proposals if p.get("priority") == "low"]

    for section_label, section_proposals in [("HIGH PRIORITY", high), ("MEDIUM PRIORITY", medium), ("LOW PRIORITY", low)]:
        if not section_proposals:
            continue
        lines.append(f"\n## {section_label}\n")
        for p in section_proposals:
            lines.append(f"### [{p.get('category', 'other')}] {p.get('title', 'Untitled')}\n")
            if p.get("description"):
                lines.append(f"{p['description']}\n\n")
            hint = p.get("implementation_hint", {})
            if hint:
                lines.append("**Implementation:**\n")
                if hint.get("file"):
                    lines.append(f"- File: `{hint['file']}`\n")
                if hint.get("function"):
                    lines.append(f"- Function: `{hint['function']}`\n")
                if hint.get("current_value") and hint.get("proposed_value"):
                    lines.append(f"- Change: `{hint['current_value']}` → `{hint['proposed_value']}`\n")
                lines.append("\n")
            ev = p.get("evidence", {})
            if ev:
                lines.append("**Evidence:**\n")
                if ev.get("sample_size"):
                    lines.append(f"- Sample size: {ev['sample_size']} trades\n")
                if ev.get("win_rate_current") is not None:
                    lines.append(f"- Current win rate: {ev['win_rate_current']:.0%}\n")
                lines.append("\n")
            if p.get("expected_impact"):
                lines.append(f"**Expected impact:** {p['expected_impact']}\n\n")
            lines.append("---\n")

    report_path.write_text("".join(lines), encoding="utf-8")
    logger.info("Saved evolution report: %s (%d proposals)", report_path, len(proposals))
    return report_path


def get_evolution_summary(data_dir: str = "data") -> dict[str, Any]:
    """Return a summary of pending proposals for injection into the evolution prompt."""
    pending = get_pending_proposals(data_dir, min_priority="low")
    by_category: dict[str, list[dict]] = {}
    for p in pending:
        cat = p.get("category", "other")
        by_category.setdefault(cat, []).append(p)

    high_priority = [p for p in pending if p.get("priority") == "high"]
    return {
        "total": len(pending),
        "by_category": {cat: len(items) for cat, items in by_category.items()},
        "high_priority_count": len(high_priority),
        "top_high_priority": high_priority[:3],  # Top 3 for prompt injection
        "recent_titles": [p.get("title", "") for p in pending[-10:]],
    }


def get_pending_proposals(
    data_dir: str = "data",
    *,
    min_priority: str = "low",
    category: str | None = None,
) -> list[dict]:
    """Load all pending proposals, optionally filtered.

    Returns flat list of proposals with their dates.
    """
    json_path = Path(data_dir) / "improvement_proposals.json"
    if not json_path.exists():
        return []

    try:
        entries = json.loads(json_path.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, OSError):
        return []

    priority_order = {"high": 3, "medium": 2, "low": 1}
    min_level = priority_order.get(min_priority, 0)

    results = []
    for entry in entries:
        date = entry.get("date", "")
        for p in entry.get("proposals", []):
            level = priority_order.get(p.get("priority", "low"), 0)
            if level < min_level:
                continue
            if category and p.get("category") != category:
                continue
            results.append({**p, "date": date})

    return results
